INSERT INTO categories VALUES (NULL, 'AMD');
INSERT INTO categories VALUES (NULL, 'America Online');
INSERT INTO categories VALUES (NULL, 'Amiga');
INSERT INTO categories VALUES (NULL, 'Anime');
INSERT INTO categories VALUES (NULL, 'Announcements');
INSERT INTO categories VALUES (NULL, 'Apache');
INSERT INTO categories VALUES (NULL, 'Apple');
INSERT INTO categories VALUES (NULL, 'Be');
INSERT INTO categories VALUES (NULL, 'Beanies');
INSERT INTO categories VALUES (NULL, 'BSD');
INSERT INTO categories VALUES (NULL, 'Bug');
INSERT INTO categories VALUES (NULL, 'Caldera');
INSERT INTO categories VALUES (NULL, 'CDA');
INSERT INTO categories VALUES (NULL, 'Censorship');
INSERT INTO categories VALUES (NULL, 'Christmas Cheer');
INSERT INTO categories VALUES (NULL, 'Comdex');
INSERT INTO categories VALUES (NULL, 'Compaq');
INSERT INTO categories VALUES (NULL, 'Corel');
INSERT INTO categories VALUES (NULL, 'Debian');
INSERT INTO categories VALUES (NULL, 'Digital');
INSERT INTO categories VALUES (NULL, 'Editorial');
INSERT INTO categories VALUES (NULL, 'Education');
INSERT INTO categories VALUES (NULL, 'Encryption');
INSERT INTO categories VALUES (NULL, 'Enlightenment');
INSERT INTO categories VALUES (NULL, 'ePlus');
INSERT INTO categories VALUES (NULL, 'Games');
INSERT INTO categories VALUES (NULL, 'GNOME');
INSERT INTO categories VALUES (NULL, 'GNU is Not Unix');
INSERT INTO categories VALUES (NULL, 'GNUStep');
INSERT INTO categories VALUES (NULL, 'Graphics');
INSERT INTO categories VALUES (NULL, 'Handhelds');
INSERT INTO categories VALUES (NULL, 'Hardware');
INSERT INTO categories VALUES (NULL, 'IBM');
INSERT INTO categories VALUES (NULL, 'Intel');
INSERT INTO categories VALUES (NULL, 'Internet Explorer');
INSERT INTO categories VALUES (NULL, 'It\'s funny.  Laugh.');
INSERT INTO categories VALUES (NULL, 'Java');
INSERT INTO categories VALUES (NULL, 'KDE');
INSERT INTO categories VALUES (NULL, 'Links');
INSERT INTO categories VALUES (NULL, 'Linux');
INSERT INTO categories VALUES (NULL, 'Linux Business');
INSERT INTO categories VALUES (NULL, 'Linux Mandrake');
INSERT INTO categories VALUES (NULL, 'Linuxcare');
INSERT INTO categories VALUES (NULL, 'Microsoft');
INSERT INTO categories VALUES (NULL, 'Movies');
INSERT INTO categories VALUES (NULL, 'Mozilla');
INSERT INTO categories VALUES (NULL, 'Music');
INSERT INTO categories VALUES (NULL, 'Netscape');
INSERT INTO categories VALUES (NULL, 'News');
INSERT INTO categories VALUES (NULL, 'Patents');
INSERT INTO categories VALUES (NULL, 'Perl');
INSERT INTO categories VALUES (NULL, 'PHP');
INSERT INTO categories VALUES (NULL, 'Privacy');
INSERT INTO categories VALUES (NULL, 'Programming');
INSERT INTO categories VALUES (NULL, 'Quake');
INSERT INTO categories VALUES (NULL, 'Quickies');
INSERT INTO categories VALUES (NULL, 'Red Hat Software');
INSERT INTO categories VALUES (NULL, 'Science');
INSERT INTO categories VALUES (NULL, 'Security');
INSERT INTO categories VALUES (NULL, 'Silicon Graphics');
INSERT INTO categories VALUES (NULL, 'Slashback');
INSERT INTO categories VALUES (NULL, 'Slashdot.org');
INSERT INTO categories VALUES (NULL, 'Space');
INSERT INTO categories VALUES (NULL, 'Spam');
INSERT INTO categories VALUES (NULL, 'Star Wars Prequels');
INSERT INTO categories VALUES (NULL, 'Sun Microsystems');
INSERT INTO categories VALUES (NULL, 'SuSE');
INSERT INTO categories VALUES (NULL, 'Technology');
INSERT INTO categories VALUES (NULL, 'Television');
INSERT INTO categories VALUES (NULL, 'The Almighty Buck');
INSERT INTO categories VALUES (NULL, 'The Courts');
INSERT INTO categories VALUES (NULL, 'The Gimp');
INSERT INTO categories VALUES (NULL, 'The Internet');
INSERT INTO categories VALUES (NULL, 'The Media');
INSERT INTO categories VALUES (NULL, 'Toys');
INSERT INTO categories VALUES (NULL, 'Transmeta');
INSERT INTO categories VALUES (NULL, 'TurboLinux');
INSERT INTO categories VALUES (NULL, 'United States');
INSERT INTO categories VALUES (NULL, 'Unix');
INSERT INTO categories VALUES (NULL, 'Upgrades');
INSERT INTO categories VALUES (NULL, 'User Journal');
INSERT INTO categories VALUES (NULL, 'VA');
INSERT INTO categories VALUES (NULL, 'Wine');
INSERT INTO categories VALUES (NULL, 'X');
INSERT INTO categories VALUES (NULL, 'Ximian');