<?php
require dirname(__FILE__) . "/../vendor/autoload.php";

function getDatabaseLink(&$link)
{
  $link = new phpcassa\Connection\ConnectionPool("RUBBoS", array("127.0.0.1:9160"));
}

function getMicroTime()
{
  list($usec, $sec) = explode(" ", microtime());
  return ((float)$usec + (float)$sec);
}

function printHTMLheader($title)
{
  include("header.html");
  print("<title>$title</title>");
}

function printHTMLHighlighted($msg)
{
  print("<TABLE width=\"100%\" bgcolor=\"#CCCCFF\">\n");
  print("<TR><TD align=\"center\" width=\"100%\"><FONT size=\"4\" color=\"#000000\"><B>$msg</B></FONT></TD></TR>\n");
  print("</TABLE><p>\n");
}

function printHTMLfooter($scriptName, $startTime)
{
  $endTime = getMicroTime();
  $totalTime = $endTime - $startTime;
  printf("<br><hr>RUBBoS (C) Rice University/INRIA<br><i>Page generated by $scriptName in %.3f seconds</i><br>\n", $totalTime);
  print("</body>\n");
  print("</html>\n");	
}

function printError($scriptName, $startTime, $title, $error)
{
  printHTMLheader("RUBBoS ERROR: $title");
  print("<h2>We cannot process your request due to the following error :</h2><br>\n");
  print($error);
  printHTMLfooter($scriptName, $startTime);      
}

function authenticate($nickname, $password, $link)
{
  $users = new phpcassa\ColumnFamily($link, "Users");
  try {
    $row = $users->get($nickname);
    $userId = $row["nickname"];
  } catch (cassandra\NotFoundException $e) {
    $userId = null;
  } catch (Exception $e) {
    die("ERROR: Authentification query failed");
  }
  if ($row['password'] == $password) {
    return $userId;
  } else {
    return null;
  }
}


function getUserName($uid, $link)
{
  return $uid;
}

?>
